### ISSUE TITLE
Unindexed bag error

### ISSUE THREAD

**Issue by scabbed-wings** [jmscslgroup/bagpy#8]
Is this a problem related with the file properties?

The call I've done is the following: b = bagreader('C:/Users/XXX/Desktop/XXXX/rosbag.bag')

**Comment by rahulbhadani** [comment]
It looks like your bag file is corrupted or the recording was stopped prematurely. You might want to look up on how to reindex bag files. In addition to that, `bagpy` is not meant to be used on Windows. If it works that's good, otherwise, I don't have any plan to provide support for Windows. Please read the README for requirements.

**Comment by scabbed-wings** [comment]
Thanks, it was an error on the file
